### PR TITLE
Use the correct request timeout in payload

### PR DESCRIPTION
**Pull request by christophwitzko**

### CODE REVIEW

**Comment by domenukk** [comment]
We should probably increase the overall timeout, then? 10s seems tight

**Review by domenukk — APPROVED** [review]

**Comment by ldruschk** [comment]
> We should probably increase the overall timeout, then? 10s seems tight

I think 10s should be plenty, given that this is per method (meaning consecutive putflag and getflag have 20s total) and enochecker_test is usually run with a network without noteworthy latency, anything that takes more than 10s will probably cause issues under real circumstances with higher latency and retransmissions due to network congestion.

**Comment by domenukk** [comment]
The python checkerlib adds 5 seconds padding as we had problems with delayed scheduling in the past, this leaves 5 seconds per method, not a lot if people want to do ocr...

**Comment by christophwitzko** [comment]
Thanks for the quick merge 🎉 
Can you trigger a new release, so my CI workflow can pick up this fix 🙏

**Pull request merged**
